### ISSUE TITLE
implement coreads()

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#103]
We are currently using `trending(bibcode:XXX)` to get a list of coread articles, but by construction this is an incomplete list due to truncation via the MoreLikeThis operator.

We would like to have a proper list of coread articles with scores reflecting the measure of reader overlap, just like ADS classic does it, no truncation applied.  We will call this the `coreads()` operator and use it for the coread link in abstract pages.

As an example, consider 2017arXiv170306870H which is currently the most read article in ADS, but has NO co-reads in BBB (660,000 in classic).

Possibly related to #31.

**Comment by romanchyla** [comment]
implemented in 40.2.0.0
