### ISSUE TITLE
author:"acco*" vs. author:"acco*,*"

### ISSUE THREAD

**Issue by romanchyla** [romanchyla/montysolr#119]
the first one doesn't return hits

also, check author:"a*"

**Comment by aaccomazzi** [comment]
Bump. This affects searches for collaborations, and makes the SE return very different results in the following queries:
```
author:"Planck*"
author:"Planck*,"
author:"Planck*,*"
```
Obviously we don't want the author to be forced to use the last two forms.

Reference: https://v2.hiverhq.com/permalink/fc6b85e65d3001c5002cc0dfb58390b1
