### ISSUE TITLE
Acronym expansion included in exact searches: bug or feature?

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#184]
A search for `=full:BLAST` returns only those documents that contain the acronym BLAST and its meaning ("Balloon-borne Large Aperture Submillimeter Telescope"), rather than other synonyms of `blast` such as `blasted`.

Is this a bug or a feature?  Users want to know if there is any way to disable the acronym expansion at search time.

![image](https://user-images.githubusercontent.com/910261/145051575-d2e56341-274a-4371-9c23-4a5f38fcec61.png)

**Comment by romanchyla** [comment]
`=full:blast` avoid acronym expansion at search time (but also synonym expansion)

they can do `full:blast` NOT `=full:acr\:\:blast` to filter out acronyms

there is probably even an easier way....

**Comment by romanchyla** [comment]
I don't believe other synonyms aren't highlighted; if they are part of the search (and they are) they can be matched and will be then retunred in the highliths -- but it is sampling process
