### ISSUE TITLE
Asymmetry in NEAR operator

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#187]
I had assumed that the NEAR operator returns documents where the two operands are within a few words of each other (3 or 5).  However, tests using NEAR within `body`, `abstract` and `full` show that a query of `A NEAR B` is different than a query of `B NEAR A`.  Example: `body:(crater NEAR antoniadi) body:(antoniadi NEAR crater)`

A possible explanation for this might be that this is an effect of synonym expansion.

**Comment by romanchyla** [comment]
you are right, i've just fixed it 7aa2d9dc
