### ISSUE TITLE
Strange effect of parenthesis on search results with facets

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#23]
The following query:
```
stephen murray
```
currently returns 13085 records (seems correct), 1486 of them with an author_facet_hier value of "0/Murray, S" (also seems correct).  So if we then issue the following query:
```
stephen murray author_facet_hier:"0/Murray, S"
```
we get back the expected 1486 records.  HOWEVER, when we modify the query to be:
```
(stephen murray) author_facet_hier:"0/Murray, S"
```
only 105 records are returned.

**Comment by romanchyla** [comment]
i tried different combinations and they have the same weird effect:

```
(stephen murray) author_facet_hier:"0/Murray, S"
(stephen murray) (author_facet_hier:"0/Murray, S")
author_facet_hier:"0/Murray, S" (stephen murray)
```

**Comment by romanchyla** [comment]
the problem was with the logic processing clauses - the auto-expansion unfielded-search foo was not being applied inside clauses (if some conditions were not met) - so i've fixed that and while on it, updated =(foo bar)
