### ISSUE TITLE
Missing results for author:"Last, F M"

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#27]
By design, the following query should return no results:

```
author:"kurtz, michael j" -author:"kurtz, m j"
```

But instead we get 8 papers in which Mike's first name is spelled out and the middle initial is missing.

**Comment by romanchyla** [comment]
the following will negate the first premise:

author:"kurtz, michael j" -author:"kurtz"
author:"kurtz, michael j" -author:"kurtz, m"
author:"kurtz, michael j" -author:"kurtz, michael"

but i'd expect these two queries to find the same number of results (or the shorter one to get more, but it is the opposite):

author:"kurtz, michael j"  -> 317 papers
author:"kurtz, m j" -> 312 

i wonder if there is some whitespace involved...

**Comment by aaccomazzi** [comment]
Any headway on this?  I can't label it as a bug at the moment or assign a milestone.

**Comment by romanchyla** [comment]
I added you as administrator. I'm surprised it is not acyivated. No, im
afraid no progress has been made on this front yet

**Comment by aaccomazzi** [comment]
Turning on debugging shows the problem I believe:
```
"parsedquery": "author:kurtz, m j author:kurtz, m j* RegexpQuery(author:/kurtz, m[^\\s]+ j/) RegexpQuery(author:/kurtz, m[^\\s]+ j .*/) author:kurtz, m author:kurtz,",
```
The fourth term should be replaced with this one:
```
RegexpQuery(author:/kurtz, m[^\\s]+ j.*/)
```
(no space between "j" and ".*").  With this change, I don't think we need the third term (author:/kurtz, m[^\\s]+ j/), because it should be caught by this already.

**Comment by romanchyla** [comment]
also see: #57

**Comment by aaccomazzi** [comment]
Not quite there yet.  The query `author:"kurtz, m j"` now expands to this:
```
author:"kurtz, m j" author:"kurtz, m j*" RegexpQuery(author:/kurtz, m[^\\s]+ j.*/) author:"kurtz, m" author:"kurtz,"
```
We are missing the following search term:
```
RegexpQuery(author:/kurtz, m[^\\s]+/)
```
You can verify this by issuing the query:
```
author:"kurtz, michael j" -author:"kurtz, m j"
```
Which should return no results.

**Comment by romanchyla** [comment]
just a final word of caution, after the `fix` for this case, precision (IMHO) suffers

`author:"adamguk, m karel"`

before the change, we have found 6 variants:

```
// "adamguk, m karel" numFound=6
          //      60  Adamguk,                61  Adamguk, M.             64  Adamguk, Molja Karel   
          //      65  Adamguk, M Karel        66  Adamguk, Molja K        67  Adamguk, M K 
```

after the change, we include 2 more names (`Adamguk, Marel` and `Adamguk, Molja`)

```
// "adamguk, m karel" numFound=8
                             //  60	Adamguk,                61	Adamguk, M.             62	Adamguk, Marel         
                             //  63	Adamguk, Molja          64	Adamguk, Molja Karel    65	Adamguk, M Karel       
                             //  66	Adamguk, Molja K        67	Adamguk, M K 
```
