### ISSUE TITLE
first_author:"kurtz, m j" and author:"^kurtz, m j" give different results

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#30]
This does not happen under other search variations (e.g. first_author:"kurtz, michael j").  Possibly related to issue #27

**Comment by romanchyla** [comment]
i have to check the analyzers - there is probably some slight difference in the definition of the first_author and author

https://ui.adsabs.harvard.edu/#search/q=author%3A%22%5EMcFadden%2C+L.%22+year%3A2015&sort=date+desc

https://ui.adsabs.harvard.edu/#search/q=author%3A%22%5EMcFadden%2C+L.+A.%22+year%3A2015&sort=date+desc
