### ISSUE TITLE
review and pare down translation rules from schema.xml

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#37]
First-hand experience in searching the database indicates that using the current translation rules for ads_text generates too many spurious results (and can't be turned off via the "=" prefix).  For example:

```
<charFilter class="solr.PatternReplaceCharFilterFactory"
                                        pattern="\b(?i:(N|NGC)(-|\s+)([0-9]+[A-Z]*))\b" replacement="NGC-$3" />
```

which causes any search for "NGC 1" to return all instances of "N 1", making this pretty useless.

**Comment by romanchyla** [comment]
@aaccomazzi the "N 1" is pretty ambiguous, would you mind me modifying the regex to only care for `NGC-x`?  but it would ignore the `N\d` results then...

**Comment by aaccomazzi** [comment]
Yes, I think we should remove the "N" case and just normalize "NGC".
