### ISSUE TITLE
Bug in combination of virtual field, "OR" boolean logic, and acronym

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#45]
The query `full:(VLBA OR Chandra)` fails due to incorrect parsing and re-mapping of the query into the proper search fields with synonym expansion.

See also https://github.com/adsabs/issues/issues/83

**Comment by aaccomazzi** [comment]
To further document the problem, the bug seems to appear in cases when all of these conditions are true:

1. field being searched is virtual (i.e. it gets expanded by the parser into multiple fielded searches)
2. one of the tokens being searched has a synonym or acronym
3. a boolean "OR" is used to combine both

Examples which show when the bug is in play and AQP's parsedquery:
```
abs:(foo OR bar)    BUG:    (abstract:foo title:foo keyword:foo) abstract:bar abstract:syn::bar
abs:(foo OR baz)    OK:     (abstract:foo title:foo keyword:foo) (abstract:baz title:baz keyword:baz)
abs:(HST OR baz)    BUG:    abstract:acr::hst abstract:syn::acr::hst abstract:syn::hubble space telescope (abstract:baz title:baz keyword:baz)
```
Where "foo" and "baz" have no synonyms/acronyms, "bar" has synonyms, and "HST" has acronyms and synonyms

**Comment by romanchyla** [comment]
fixed
