### ISSUE TITLE
Incorrect parsing of pubdate field

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#65]
The search `pubdate:[2014-00 TO 2014-06]` gives the same results as `pubdate:[2014-00-00 TO 2014-06-00]` but different results than `pubdate:[2014-00-0 TO 2014-06-0]`

Turning debugging on shows that the parser interprets the two dates differently
```
pubdate:[2014-00-00 TO 2014-06-00] -> date:[1388534400000 TO 1401667199000]
pubdate:[2014-00-0 TO 2014-06-0]   -> date:[1385856000000 TO 1401580799000]
```

**Comment by aaccomazzi** [comment]
Possibly related to this, `pubdate:[2016-01-01 TO 2016-01-31]` returns 0 results whereas `pubdate:[2016-01-1 TO 2016-01-31]` returns the expected results, as documented in https://github.com/adsabs/issues/issues/107

**Comment by romanchyla** [comment]
ended up extending the existing mechanism; now we can *at will* offer translation of any date/timestamp field; it's just a config change

commit: 68e9649
