### ISSUE TITLE
No results for trending(bibcode) -bibcode

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#66]
The co-reads link available from a BBB abstract page is computed using the following formula, for a given bibcode:
```
trending(bibcode:2016arXiv161102269V) -bibcode:2016arXiv161102269V"
```
This seems to work in most cases.  However, for the bibcode above it currently fails by returning 0 results even if the record has a read_count of over 40k, and hance should return all the documents read by those 40k readers.

**Comment by romanchyla** [comment]
we'll select the document with 40K readers; collect all the readers and pass them onto the MoreLikeThis query; the query is configured to disregard any term (reader) which occurs in less than 2 papers (i.e. pick only readers that read more than two papers)

the initial document contains readers that are present in at least 2 documents - so this looks like a bug; very likely the implementatiion of the collector - `AbstractSecondOrderCollector.ABS_VALUE`; but it will be very hard to debug

**Comment by romanchyla** [comment]
i've added (some time ago) a sort by classic_factor, as we disussed it
