### ISSUE TITLE
author:"Penaloza, C."  does not find records by "Peñaloza, C."

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#79]
It is surprising that we don't generate a synonym that takes care of this.  To test, try the query
```
author:"Peñaloza, C."  NOT author:"Penaloza, C." 
```

**Comment by aaccomazzi** [comment]
Other similar author search issues: `author:"Grudić, M"` vs. `author:"Grudic, M"`.  The first one generates 5 results, the second just 1 (which is in the set of 5).

**Comment by romanchyla** [comment]
we can only go from 'n' to 'ñ' if it is a part of a synonym file; i've checked the synonyms and neither panaloza nor grudic are there `/proj/ads/abstracts/config/solr`

we can't really generate the 'upgrade' cominations; literally every letter has one or more possible readings and that goes out of hand very quickly.

afaik solr is doing the right thing, but we need a better synonym file if those those authors are to be found

**Comment by romanchyla** [comment]
resolved in the new release
