### ISSUE TITLE
=author:"^smith, a m s" produces the same results as author:"^smith, a m s"

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#82]
The exact author search indicator ("=") seems to be ignored.
In contrast, `=first_author:"smith, a m s"` works just fine.

**Comment by romanchyla** [comment]
the "^something" is a terrible thing that is responsible for ugly workarounds; i did fix it but i'd rather see people use: `pos(=author:"smith, a m s", 1)`
