### ISSUE TITLE
`author:mason, j p` builds (invalid?) regex query

### ISSUE THREAD

**Issue by romanchyla** [romanchyla/montysolr#94]
the query parser generates a query that should have found the author `SpanMultiTermQueryWrapper(author:/mason, j[^\\s]+ p.*/)`

the guy is indexed as `mason, james paul` -- the regex doesn't work any more `author:/mason, j[^\\s]+ p.*/`

`/a.*/` works but `/a[^\s*/` doesn't

and `author:/mason, j[^\\s]+/` selects `Mason, Jarad A`

**Comment by spacemansteve** [comment]
consider testing with 2014ApJ...789...61M

**Comment by spacemansteve** [comment]
All the author fields are tokenized.  Solr does not really [support](https://1opensourcelover.wordpress.com/2013/09/29/solr-regex-tutorial/
) regex matching across word boundaries since the boundaries don't really exist.
Do we want to change the regex to be something like 
```
author:/mason, j[^\\s]+.*p.+/ 
```

**Comment by spacemansteve** [comment]
While indexing we do [not apply](https://github.com/romanchyla/montysolr/blob/master/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml#L59) a whitespace tokenizer so each author should be a single token.  This preserves whitespace in the author name.

**Comment by spacemansteve** [comment]
calling dumpDoc results in the error  java.lang.NoClassDefFoundError: org/apache/lucene/index/AtomicReader.  AtomicReader was in Solr 4 but it is not in Solr 6.

**Comment by spacemansteve** [comment]
[junit4] ERROR   0.03s J0 | TestCitationCacheReaderWriter.testCacheLoad <<<
   [junit4]    > Throwable #1: java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/Sp\
acemanSteve/code/eclipse/workspace/montysolr/montysolr/build/solr-download/apache-solr-63/solr/build/contrib/solr-adsab\
s/test/J0/citation-cache9087268928624635552/collection1/conf" "write")

**Comment by spacemansteve** [comment]
I do not see any mention of predefined character classes (like \d or \s) in Lucene's [Regexp](https://lucene.apache.org/core/6_3_0/core/index.html?org/apache/lucene/index/AutomatonTermsEnum.html).
